import { CurationData, Article } from '../types.ts';

/**
 * Format a single article into the required markdown specification
 */
export function formatSingleArticleMarkdown(article: Article, index?: number): string {
  const cleanTitle = article.title.replace(/^📌\s*/, '').trim();
  const bullets = article.keyPoints && article.keyPoints.length > 0
    ? '\n' + article.keyPoints.map(p => `  • ${p}`).join('\n')
    : '';

  return `### ${index !== undefined ? `${index + 1}. ` : ''}📌 **${cleanTitle}**
- 🏷️ **출처/분야:** ${article.source} | ${article.categoryTag || 'IT/트렌드'}
- 📝 **핵심 요약:**
  ${article.summary}${bullets ? '\n' + bullets : ''}
- 🔗 **원문 링크:** [${article.source} 원문 바로가기](${article.url})
  ${article.url}`;
}

/**
 * Format the entire curation result into clean, mobile-optimized structured markdown
 */
export function generateFullMarkdown(data: CurationData): string {
  const articlesMd = data.articles
    .map((art, idx) => formatSingleArticleMarkdown(art, idx))
    .join('\n\n---\n\n');

  return `# 📰 [핵심 브리핑] ${data.keyword} 최신 뉴스 Top 3
> 📅 **조회 일자:** ${data.searchDate}  
> 💡 **종합 분석:** ${data.overallSummary}

---

${articlesMd}

---
*Generated by AI 뉴스 핵심 요약 큐레이터 (Google Search Grounding)*`;
}
